optimizely/android-sdk

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
event-handler/src/androidTest/java/com/optimizely/ab/android/event_handler/EventDAOTest.java
event-handler/src/androidTest/java/com/optimizely/ab/android/event_handler/EventDispatcherTest.java
event-handler/src/androidTest/java/com/optimizely/ab/android/event_handler/EventSQLiteOpenHelperTest.java
event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventDAO.java
event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventIntentService.java
event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventSQLiteOpenHelper.java

These changes should enable multiple `OptimizelyManager` and `AndroidOptimizely` parings for each project.  Some users might find it convenient to be able to run multiple Optimizely projects inside of the same app.  For example, one project might test the copy of notifications shown from Android services and another project is used for `Activity` testing.
```
OptimizelyManager manager1 = OptimizelyManager.Builder("projectId1").build();
OptimizelyManager manager2 = OptimizelyManager.Builder("projectId2").build();
AndroidOptimizely optimizely1 = manager1.getOptimizely();
AndroidOptimizely optimizely2 = manager2.getOptimizely();
assert manager1 != manager2;
assert optimizely1 != optimizely2;
```
We were storing events for all projects in one table.  While, this would still work I think it's …

Allow multiple managers

---

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/DataFileClientTest.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/DataFileClient.java
build.gradle
event-handler/src/androidTest/java/com/optimizely/ab/android/event_handler/EventDispatcherTest.java
event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventClient.java
event-handler/src/test/java/com/optimizely/ab/android/event_handler/EventClientTest.java
shared/src/androidTest/java/com/optimizely/ab/android/shared/ClientTest.java
shared/src/main/java/com/optimizely/ab/android/shared/Client.java
test-app/src/main/java/com/optimizely/ab/android/test_app/MyApplication.java

Datafile download and event dispatch were both happening synchronously on background threads.  We simply need to make the client's request method handle exponential backoff internally.  As much as possible was moved into the shared library since the event client and datafile client both use the same client core.
Tested e2e manually via logs and putting a phone into airplane mode.  There is no easy way to programmatically cause network failures.  Added more unit test coverage.

Sets up exponential backoff for event dispatch and datafile download

---

event-handler/src/androidTest/java/com/optimizely/ab/android/event_handler/ServiceSchedulerTest.java
shared/src/main/java/com/optimizely/ab/android/shared/ServiceScheduler.java

We had a small bug that prevented the interval of services from being changed once they are scheduled the first time.

Allows service intervals to be changed after they are scheduled

---

.idea/dictionaries/jdeffibaugh.xml
event-handler/src/main/AndroidManifest.xml
event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventRescheduler.java
event-handler/src/test/java/com/optimizely/ab/android/event_handler/EventReschedulerTest.java
test-app/src/main/java/com/optimizely/ab/android/test_app/MyApplication.java

Only will happen if an event flush is scheduled.

Preemptively flush events when wifi is available if available

---

build.gradle
test-app/build.gradle
test-app/src/main/res/layout/activity_main.xml

We are open source so our repo can be mirrored in jcenter and maven central.  Users no longer need to declare our repo.

Remove optly repo

---

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/DataFileReschedulerTest.java
android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerTest.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerDataFileServiceConnectionTest.java

Since we are using the nullability of the dataFileServiceConnection to control whether we can bind we need to null it out so that subsequent start and initialize calls still try to bind the service.  
Generally, most apps will probably have one OptimizelyManager instance.  Without this change you couldn't call initialize on more than one activity.

Nulls out the dataFileService connection

---

CHANGELOG.md
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java
android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java
build.gradle

Add live variables

---

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java

It makes more sense to have this method be static as it'll be easier for the developer to use instead of having to rely on an instance. Also matches what iOS has, which is a static class method.

Make getDatafileUrl static for easier access.

---

CHANGELOG.md
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/BackgroundWatchersCache.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileCache.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileClient.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileLoader.java
event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventDispatcher.java
event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventRescheduler.java
shared/src/main/java/com/optimizely/ab/android/shared/Cache.java
test-app/src/main/java/com/optimizely/ab/android/test_app/NotificationService.java
user-profile/src/main/java/com/optimizely/ab/android/user_profile/UserProfileCacheUtils.java

cleanup javadocs, unused imports, and some coding style changes

---

.circleci/config.yml

This change enables publishing to bintray via a git tag by adding a new workflow.

new config for tags

---

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java
android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java
test-app/src/main/java/com/optimizely/ab/android/test_app/SplashScreenActivity.java

bring back getVariable(String,Integer,Double,Boolean)

---

CHANGELOG.md

Simple changes to the changelog, which wasn't updated when we did the 2.0.0 rollback and 2.0.0-beta2 release

fixing changelog to reflect 2.0.0 rollback and 2.0.0-beta2 release

---

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java

In circumstances where initialisation fails, ``OptimizelyManager`` returns a dummy ``OptimizelyClient`` which has a null ``NotificationCenter``.
Adding this annotation warns SDK users that they shouldn’t rely on a ``@NonNull NotificationCenter`` being returned, for example if they call ``addActivateNotificationListener()`` after ``initialise()`` This bit a client of mine in production so hoping this will help other users.
Android Studio now displays appropriate warnings when calling this API from Java, including from the test app. In Kotlin though the following would not compile if this annotation is added:
``optimizelyClient.notificationCenter.addActivateNotificationListener(...)``
``Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type …

Add @Nullable annotation to getNotificationCenter()

---

CHANGELOG.md

Update changelog.  This build needs to go out since 2.1.1 was not done properly.

(chore) update changelog for release

---

CHANGELOG.md
user-profile/src/main/java/com/optimizely/ab/android/user_profile/UserProfileCache.java

(fix)UPS: don't trim unless over 100 experiments in user's UPS

---

.travis.yml
android-sdk/build.gradle
build.gradle
datafile-handler/build.gradle
event-handler/build.gradle
gradle/wrapper/gradle-wrapper.properties
shared/build.gradle
test-app/build.gradle
test-app/src/main/java/com/optimizely/ab/android/test_app/MyApplication.java
user-profile/build.gradle

- Upgrade to use latest build and tools.
- Compatibility is now at Java 1 8.
Android SDK developers can use Kotlin from here on out.
- Tested with latest Java also at 1.8
Preparing for 3.0 release/

(feat): refactor gradle to use latest builds and to build for java 1.8

---

CHANGELOG.md
android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java
build.gradle

- Update changelog and gradle build to point to new release 3.0.0

(chore):Prepare for3.0

---

event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventRescheduler.java
shared/src/main/java/com/optimizely/ab/android/shared/ServiceScheduler.java

- Problems reported with EventScheduler scheduling too many jobs.
- #267

(fix):potential fix for multi scheduling of event work

---

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java

- Cleanup the try catch error for logging.
- #262

(fix):refactor the try catch for failing to load logger

---

android-sdk/build.gradle
build.gradle
datafile-handler/build.gradle
event-handler/build.gradle
proguard-rules.txt
shared/build.gradle
shared/src/main/java/com/optimizely/ab/android/shared/ServiceScheduler.java
user-profile/build.gradle

I was able to reproduce this problem turning on minify on a kotlin project.  The following rules and compile cleanups, enabled the apk to be created, installed, and ran, without issue. 
Created test apps to reproduce the issue.
- #258

(fix): this fixes proguard rules when running minifyEnabled

---

datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DefaultDatafileHandler.java

- The "what"; a concise description of each logical change
- Another change
- "THING-1234" or "Fixes #123"

Fix: Setdatafile of defaultDatafileHandler is returning null datafile 

---

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileLoader.java

- If the cached datafile is removed or corrupted, and last modified has already been set, the app won't load.
- If loading synchronously there is a similar problem where the datafile cache exists but is corrupt, it will also fail to initialize.
- #277

(fix): Corrupt datafile cache fix

---

.travis.yml
CHANGELOG.md
android-sdk/build.gradle
build.gradle
datafile-handler/build.gradle
event-handler/build.gradle
scripts/android-wait-for-emulator.sh
shared/build.gradle
test-app/build.gradle
user-profile/build.gradle

this brings the changes in the 3.1.1 release to the master branch
* fix(jackson-databind): update version
* chore: update changelog
* travis(ci): use our own emulator wait script
* more helpful output while waiting for emulator
* force trusty

fix(jackson-databind): update version (pr to master)

---

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
build.gradle

- Small fix to use Optimizely Java SDK 3.2.1 builder.withDatafile instead of deprecated methods.
- "THING-1234" or "Fixes #123"

(fix): don't use deprecated java sdk methods

---

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java

- Some developers want to initialize with their datafile and not attempt a background update.  The android documentation does not mention background update of cache.  By making this method public, we can fix a github issue as well as make the flow diagram correct since one time background updates to cache will be optional. (this does not affect periodic downloads).
- #300

(fix): make protected method public

---

CHANGELOG.md
proguard-rules.txt
test-app/proguard-rules.pro

- Since it is required in a minify.  We can probably add this rule without too much complaint.
- I generated a signed release pack with minify to insure that everything still works

fix (proguard): moved slf4j proguard keep to sdk rules

---

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileLoader.java

- Load the cached datafile in the datafile loader if the datafile is null from cdn.  This avoids loading the cached datafile in the onPostExecute of the datafile loader which is on the main thread.
- #320

(fix): Listener on task

---

CHANGELOG.md

chore: prepare for 3.5.0

---

.travis.yml
android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerTest.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
build.gradle
datafile-handler/src/androidTest/java/com/optimizely/ab/android/datafile_handler/DatafileLoaderTest.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileLoader.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileRescheduler.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DefaultDatafileHandler.java
event-handler/build.gradle
shared/build.gradle
shared/src/main/java/com/optimizely/ab/android/shared/ServiceScheduler.java
test-app/src/main/java/com/optimizely/ab/android/test_app/SplashScreenActivity.java

- Eliminate piling up of datafile calls.  Use latest tools. 
- Lots of manual testing including taking the device offline for long periods of time.

fix: update to latest build tools. slight refactor of datafile service.

---

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java
android-sdk/src/debug/res/raw/validprojectconfigv4
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java
build.gradle

- add new APIs (getFeatureVariableJSON, getAllFeatureVariables)
- add new notification type (all-feature-variables)
- Add mavenLocal() to supported repositories for local development
- Bump core SDK to 3.5.0-beta
- Added unit tests

feat: add getFeatureVariableJSON and getAllFeatureVariables apis

---

android-sdk/build.gradle
datafile-handler/build.gradle
event-handler/build.gradle
shared/build.gradle
user-profile/build.gradle

- javadoc task was failing.  These changes are needed for releasing and building javadocs.
Needed for publish.  Published locally.

fix: upgrade to 6.x gradle syntax for javadocs

---

test-app/build.gradle

- fresh builds will fail with lint errors in test-app.  suppress abort on failure.

fix: add line so test-app does not abort on lint errors

---

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerBuilderTest.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java

-  move check to datafileConfig check.
-  simple change.
- Added unit tests to builder test.
- "Fixes #355 "

fix: remove erroneous error if project id and sdk key are null.

---

CHANGELOG.md

- 3.10.1 release note misses a bug fix for empty rollout cases.
- "OASIS-7997"

chore: add a missing bug-fix note

---

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerTest.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerBuilderTest.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DefaultDatafileHandler.java
shared/src/main/java/com/optimizely/ab/android/shared/WorkerScheduler.java

- This fixes the bug that a polling worker scheduled before is not disabled when Optimizely is initialized again with polling disabled.
- When Optimizely is initialized, stop the previous worker and then restart it again only when polling is enabled.
- Unit tests
- OASIS-8118

fix(DatafileHandler): unschedule background polling worker when interval is not set

---

README.md

Jcenter removed the deadline for old SDK versions

chore: remove Jcenter deadline for old SDK versions

---

datafile-handler/src/androidTest/java/com/optimizely/ab/android/datafile_handler/DatafileReschedulerTest.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileRescheduler.java

- Move config-file read to a background thread when DatafileRescheduler is invoked. 
This will fix a potential source of ANRs.
- Add unit tests validating datafile worker scheduled properly from DatafileRescheduler.
- OASIS-8128

fix(datafileRescheduler): move config file read to a background thread

---

README.md

Updated info to docs and updated jcenter deprecation info.
N/A
N/A

Update info about jcenter/mavencentral

---

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyDefaultAttributes.java
test-app/build.gradle
test-app/src/main/resources/android-logger.properties

- (android SDK package name) -> android SDK version 
- (app version + serail-id) -> app version
These default attributes are filtered out from events unless attributes are set in the project configuration.

fix: change default attributes to more meaningful values

---

.github/workflows/android.yml

- publish is not trigger because "v" in tag checking

chore: remove v from release tag check

---

event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventHandlerUtils.java

- StrictMode detects leaks with inflater and deflater.
- Add end() calls at the end of inflate/deflate
- Pass with existing compress/decompress
- Test with StrictMode 
- [ISSUE-419](https://github.com/optimizely/android-sdk/issues/419)

fix: call end inflater/deflater to avoid leaks

---

datafile-handler/src/androidTest/java/com/optimizely/ab/android/datafile_handler/DatafileClientTest.java
datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileClient.java
event-handler/src/androidTest/java/com/optimizely/ab/android/event_handler/EventClientTest.java
event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventClient.java

Set timeouts to UrlConnections for DatafileClient and EventClient so they can release resources when connection failed (0 by default, which is no timeout).
- Add unit tests for UrlConnections timeout
- [OASIS-8568](https://jira.sso.episerver.net/browse/FSSDK-8568)
- https://github.com/optimizely/android-sdk/issues/429

fix(DatafileClient): add timeouts to UrlConnections

---

android-sdk/build.gradle
android-sdk/src/main/AndroidManifest.xml
datafile-handler/build.gradle
datafile-handler/src/main/AndroidManifest.xml
event-handler/build.gradle
event-handler/src/main/AndroidManifest.xml
shared/build.gradle
shared/src/main/AndroidManifest.xml
test-app/build.gradle
test-app/src/main/AndroidManifest.xml
user-profile/build.gradle
user-profile/src/main/AndroidManifest.xml

- Reverted putting namespace in gradle file instead of manifiest (see PR 437)
- FSSDK-8688

Fix: Reverted putting namespace in gradle file instead of manifiest 

---

.github/workflows/android.yml

Fix github workflow to skip testing for SNAPSHOT and publish tasks.
- FSSDK-0000

chore: skip unit and fsc tests for snapshot and publish

---

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerBuilderTest.java
build.gradle

Pass android ODP commonData and commonIdentifiers to Java ODPManager builder. 
- Add a unit test/
- FSSDK-8768

feat(ATS): pass odp common data and identifiers to java core

---

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/ODPIntegrationTest.java
android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/ODPIntegrationUpdateConfigTest.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
odp/src/main/java/com/optimizely/ab/android/odp/DefaultODPApiManager.kt
odp/src/main/java/com/optimizely/ab/android/odp/ODPSegmentClient.kt

- For ODPConfig update, send an internal notification when project config is updated (in addition to public NotificationCenter).
- A few more unit test cases are added for OPD integration tests.
- Unit test validating ODPConfig updated when a new datafile is downloaded.
- [FSSDK-8906](https://jira.sso.episerver.net/browse/FSSDK-8906)

fix(ATS): send an internal notification when project config is updated

---

odp/src/androidTest/java/com/optimizely/ab/android/odp/ODPEventClientTest.kt
odp/src/androidTest/java/com/optimizely/ab/android/odp/ODPSegmentClientTest.kt
odp/src/main/java/com/optimizely/ab/android/odp/ODPEventClient.kt
odp/src/main/java/com/optimizely/ab/android/odp/ODPSegmentClient.kt
shared/src/androidTest/java/com/optimizely/ab/android/shared/ClientTest.java
shared/src/main/java/com/optimizely/ab/android/shared/Client.java

Fix retries for ODP api access
- no retry on fetchQualifiedSegments failure
- max 3 retries on ODP event dispatch
- add unit tests for validating retry settings in OdpSegmentClient and OdpEventClient
- manually validated with http://httpstat.us
- [FSSDK-9103](https://jira.sso.episerver.net/browse/FSSDK-9103)

[FSSDK-9103] feat(ATS): fix retries for ODP segment and event API calls.

---

proguard-rules.txt
test-app/build.gradle
test-app/src/main/java/com/optimizely/ab/android/test_app/MyApplication.kt
test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInJava.java
test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInKotlin.kt

Add a proguard rule to keep ODPEvent.
Add sample codes for ODP.
- FSSDK-123

fix(ats): add proguard rule for ODPEvent

---

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java

- This will gracefully log the exception that was reported in issue #458 
All tests should pass
- [FSSDK-9406](https://jira.sso.episerver.net/browse/FSSDK-9406)

[FSSDK-9406] fix: Added catch block to capture resource not found exception

---

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/ODPIntegrationUpdateConfigTest.java
android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyClientEngineTest.java
android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerEventHandlerTest.java
android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerTest.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClientEngine.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerBuilderTest.java
android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerIntervalTest.java
build.gradle
shared/build.gradle

Fix to support arbitrary client names to be included in logx and odp events.
This fix depends on the change in the java-sdk core (https://github.com/optimizely/java-sdk/pull/524)
Add unit tests for new APIs.
Pass all existing tests.
- FSSDK-9432

[FSSDK-9432] fix: fix to support arbitrary client names to be included in logx and odp events.

---

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/ODPIntegrationUpdateConfigTest.java
android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyClientEngineTest.java
android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerEventHandlerTest.java
android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerTest.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClientEngine.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerBuilderTest.java
android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerIntervalTest.java
build.gradle
shared/build.gradle

Fix to support arbitrary client names to be included in logx and odp events.
This fix depends on the change in the java-sdk core (https://github.com/optimizely/java-sdk/pull/524)
Add unit tests for new APIs.
Pass all existing tests.
- FSSDK-9432

Revert "[FSSDK-9432] fix: fix to support arbitrary client names to be included in logx and odp events."

---

.github/workflows/android.yml

- Assigned the value of `github.head_ref` to an intermediate environment variable and employ that variable in the shell script.
- https://securitylab.github.com/research/github-actions-untrusted-input/
- https://codeql.github.com/codeql-query-help/javascript/js-actions-command-injection/
- https://securitylab.github.com/advisories/GHSL-2023-110_Wing_Language/
- N / A
- [FSSDK-10230](https://jira.sso.episerver.net/browse/FSSDK-10230)

[FSSDK-10230] fix: GitHub slug `head_ref` vulnerability resolved

---

odp/src/androidTest/java/com/optimizely/ab/android/odp/ODPSegmentClientTest.kt
odp/src/main/java/com/optimizely/ab/android/odp/ODPSegmentClient.kt

- As per demand of HSBC, forwarding exception for unexpected sever response from ODP 
- [FSSDK-10523](https://jira.sso.episerver.net/browse/FSSDK-10523)

[FSSDK-10523] forward exceptions for un-expected response from ODP

---

.github/workflows/android.yml
README.md

- Android integration test fixed
- [FSSDK-10523](https://jira.sso.episerver.net/browse/FSSDK-10523)

FSSDK-10523 fix: integration test fix

---

CHANGELOG.md
README.md

- Prepare for release 4.0.4
- N/A
- [FSSDK-10674](https://jira.sso.episerver.net/browse/FSSDK-10674)

[FSSDK-10674] chore: prepare for release 4.0.4

---

README.md
build.gradle

- bump java sdk to version 4.2.0
- all existing tests should pass
- FSSDK-10769

[FSSDK-10769] bump java sdk to version 4.2.0

---

CHANGELOG.md
README.md

- UPS batching for decideAll and decideForKeys methods
- All previous test cases should be passed
- [FSSDK-10841](https://jira.sso.episerver.net/browse/FSSDK-10841)

[FSSDK-10841] chore: release 4.1.0

---

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java
android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerBuilderTest.java
android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerIntervalTest.java
odp/src/androidTest/java/com/optimizely/ab/android/odp/VuidManagerTest.kt
odp/src/main/java/com/optimizely/ab/android/odp/VuidManager.kt
shared/src/main/java/com/optimizely/ab/android/shared/OptlyStorage.java

- With this PR, VUID can be enabled/disabled independently of ODP
- added news tests and updated affected old tests
- FSSDK-10758

 [FSSDK-10758] implement vuid configuration independent of odp

---

.github/workflows/android.yml
.github/workflows/build.yml
CONTRIBUTING.md
README.md
build.gradle

- Remove travis build status
- Rename `testAllModulesTravis` task to `testAllModules`
- N/A
- [FSSDK-11076](https://jira.sso.episerver.net/browse/FSSDK-11076)

[FSSDK-11076] chore: remove travis details from doc

---

android-sdk/build.gradle
build.gradle

- OSSRH has reached end of life on June 30, 2025.
- To minimize changes while enabling compatibility with the new portal, add the io.github.gradle-nexus.publish-plugin.          - This plugin automates staging management and works with the OSSRH Staging API for transitional support.
- https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#overview
- FSSDK-11782

[FSSDK-11782] chore: migrate publishing process from OSSRH to maven central portal
