optimizely/android-sdk

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/DataFileClientTest.java, android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/DatafileServiceTest.java, android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerTest.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/DataFileLoader.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/DataFileService.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
This makes it so that our datafile manager uses the versioned datafile URL to retrieve the datafile. 
We also expose an API on the manager to get the url of the datafile that it expects to use.
=> Add versioned datafile path and public API to retrieve it.

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java
=> Move activateExperiment param in live variable getters

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/BackgroundWatchersCacheTest.java, android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/DataFileCacheTest.java, android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/DataFileClientTest.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/BackgroundWatchersCache.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/DataFileCache.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/DataFileClient.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventClient.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventDAO.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventDispatcher.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventSQLiteOpenHelper.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/OptlyEventHandler.java, shared/src/androidTest/java/com/optimizely/ab/android/shared/CacheTest.java, shared/src/main/java/com/optimizely/ab/android/shared/Cache.java, shared/src/main/java/com/optimizely/ab/android/shared/Client.java, shared/src/main/java/com/optimizely/ab/android/shared/ServiceScheduler.java, test-app/src/androidTest/java/com/optimizely/ab/android/test_app/MainActivityEspressoTest.java, test-app/src/main/java/com/optimizely/ab/android/test_app/MainActivity.java, user-profile/src/androidTest/java/com/optimizely/ab/android/user_profile/UserProfileCacheTest.java, user-profile/src/androidTest/java/com/optimizely/ab/android/user_profile/WriteThroughCacheFactoryTest.java, user-profile/src/main/java/com/optimizely/ab/android/user_profile/UserExperimentRecordCache.java
This fixes a number of crashes and bugs that our beta customer pointed out.
=> Fix various bugs and crashes.

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/BackgroundWatchersCacheTest.java, android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/DataFileCacheTest.java, android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/DataFileClientTest.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/BackgroundWatchersCache.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/DataFileCache.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/DataFileClient.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventClient.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventDAO.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventDispatcher.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventSQLiteOpenHelper.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/OptlyEventHandler.java, shared/src/androidTest/java/com/optimizely/ab/android/shared/CacheTest.java, shared/src/main/java/com/optimizely/ab/android/shared/Cache.java, shared/src/main/java/com/optimizely/ab/android/shared/Client.java, shared/src/main/java/com/optimizely/ab/android/shared/ServiceScheduler.java, test-app/src/androidTest/java/com/optimizely/ab/android/test_app/MainActivityEspressoTest.java, test-app/src/main/java/com/optimizely/ab/android/test_app/MainActivity.java, user-profile/src/androidTest/java/com/optimizely/ab/android/user_profile/UserProfileCacheTest.java, user-profile/src/androidTest/java/com/optimizely/ab/android/user_profile/WriteThroughCacheFactoryTest.java, user-profile/src/main/java/com/optimizely/ab/android/user_profile/UserExperimentRecordCache.java
Re-opening this to squash merge instead of just merging.
=> Fix various crashes and bugs

CHANGELOG.md
=> Add changelog entry for 0.4.1.

CHANGELOG.md
=> Add changelog entry for 0.4.1. (#63)

shared/src/main/java/com/optimizely/ab/android/shared/Cache.java
=> Fix javadoc for Cache class.

test-app/src/main/java/com/optimizely/ab/android/test_app/MyApplication.java
=> Add documentation for not persisting userId in teset app for QA purposes

test-app/src/main/res/layout/activity_event_confirmation.xml
=> Change wording on event sent confirmation screen in test app

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java, android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerBuilderTest.java
=> Enforce minimum datafile refresh time to 60 seconds

.travis.yml, build.gradle
=> Allow test app tests to be run in 'testAllModules' gradle task

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java, build.gradle
=> Change 'getVariableFloat' to 'getVariableDouble'

user-profile/src/androidTest/java/com/optimizely/ab/android/user_profile/AndroidUserProfileTest.java, user-profile/src/androidTest/java/com/optimizely/ab/android/user_profile/WriteThroughCacheFactoryTest.java, user-profile/src/main/java/com/optimizely/ab/android/user_profile/AndroidUserProfile.java
=> Change key to ID in all variable names within UserProfile

CHANGELOG.md
=> Update changelog to include 0.5.0

README.md, test-app/README.md
@optimizely/fullstack-devs @mauerbac
=> Fix READMEs

test-app/build.gradle
=> Bump demo app SDK version

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClientEngine.java
=> Add missing JavaDoc to new class

shared/proguard-rules.pro
creating a PR to see if the build passes. the build was failing in Phabricator
=> Elliot/revert proguard OASIS-1098

CHANGELOG.md, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java, build.gradle
=> Add event tags to track API

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerTest.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
Finally ready to merge https://phabricator.optimizely.com/D14979
=> Additional unit test for passing in a null or empty string datafile

.travis.yml, build.gradle
=> Fix travis-ci after upgrading build tools

.travis.yml, CHANGELOG.md, android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerTest.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Release version 1.3.0

android-sdk/build.gradle, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClientEngine.java
Also increase max heap size for emulator and remove unnecessary annotation
@optimizely/fullstack-devs
=> Fix Javadoc

android-sdk/src/main/java/com/optimizely/ab/android/sdk/DataFileClient.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
=> Fix various crashes in the top-level APIs

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
=> Handle exceptions in top-level APIs

CHANGELOG.md, build.gradle
bintray upload isn't working because of typo.
=> Misspelling fixes

event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventDAO.java
=> Remove unnecessary close()

test-app/proguard-rules.pro
Add proguard rules to test-app
OASIS-1515
=> Add Proguard rules from the documentation to the test app

datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileService.java
=> Replace `getClass()` which uses reflection with explicit class

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyManagerTest.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
OASIS-1516
@optimizely/fullstack-devs
=> Handle errors so apps don't crash

datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileCache.java, datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileLoader.java, shared/src/androidTest/java/com/optimizely/ab/android/shared/CacheTest.java, shared/src/main/java/com/optimizely/ab/android/shared/Cache.java
Refactor `exists()`
Other minor cleanup
@optimizely/fullstack-devs
=> Close file streams in Cache to release resources and prevent crashes

test-app/proguard-rules.pro
=> Uncomment proguard rule in test-app

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java, android-sdk/src/main/resources/android-logger.properties, build.gradle
OASIS-1472
@optimizely/fullstack-devs @thomaszurkan-optimizely
=> Add catch for errors when instantiating logger

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java, android-sdk/src/debug/res/raw/validprojectconfigv4, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, build.gradle
* Added Wrapper for getEnabledFeatures 
* Added its unit tests
* updated java version to 2.0.0-beta6
* updated datafile and added featureEnabled as it was not passing all unittests of due to featureEnabled was not set
=> get enabled feature pr

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java
=> Removed overloaded methods of track that were taking revenue value

build.gradle, test-app/build.gradle
All recommended package upgrades from Source Clear does not break the current code base.
- `./gradlew assemble` successfully built
- `./gradlew testAllModule` passed
- `./gradlew testAllModulesTravis` passed
- test-app passed
- Used the test app and configured it to my own experiment. I used the test app as if I were a user, and then checked the results page to see if the functionality of Optimizely on the test app still worked.
=> Source Clear Improvements

CHANGELOG.md, build.gradle
- Use Optimizely Java SDK 3.0.0-RC2
=> (choir) update changelog and build for 3.0.0-RC2

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java
docs: Improve descriptions of the public API's class, methods, and parameters.
This provides additional detail to the descriptions and consistency with readme.io.
=> docs: Improve descriptions of the public API's class, methods, and parameters. (EDU-2461)

datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileRescheduler.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/DefaultEventHandler.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventRescheduler.java, shared/src/main/java/com/optimizely/ab/android/shared/ServiceScheduler.java
- There was a problem reported about job scheduler taking a long time.  This may be due to job items accumulating in the job scheduler queue.  This is a potential fix.
Need to test on a device.
- I'm not sure there is a ticket opened yet.
=> (fix):attempt to fix potential problem with job service items piling up

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java
- Removed live variables functions, unit tests and their mapping .
=> Refact: Removed LiveVariable functions and unit tests

datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileRescheduler.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/DefaultEventHandler.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventRescheduler.java, shared/src/main/java/com/optimizely/ab/android/shared/ServiceScheduler.java
Reverts optimizely/android-sdk#243
=> Revert "(fix):attempt to fix potential problem with job service items piling up"

build.gradle, gradle/wrapper/gradle-wrapper.properties, shared/build.gradle, test-app/src/main/java/com/optimizely/ab/android/test_app/SplashScreenActivity.java
- Revert back to gradle 4.1 until we can figure out the ship task issue.
=> (fix):quick fix for 3.0 release

android-sdk/build.gradle, build.gradle, datafile-handler/build.gradle, event-handler/build.gradle, gradle/wrapper/gradle-wrapper.properties, shared/build.gradle, test-app/build.gradle, user-profile/build.gradle
- Updated gradle version of android sdk to 4.10.3
=> Gradle Update to 5.2.1

.travis.yml
This uses the script from travisci-tools repo to trigger compat suite. 
OASIS-4389
=> ci: Use travisci-tools script to trigger tests

CHANGELOG.md, build.gradle
- Update changelog and use Optimizely java sdk 3.0.1
=> (chore):updates for 3.0.1 release

build.gradle
Update Android to use the new Java 3.1.0 with the decision listeners changes.
This goes into @mnoman09 's branch. I have a passing custom FSC build here: https://travis-ci.com/optimizely/android-testapp/builds/110936682
=> upgrade to new Java 3.1.0.

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, build.gradle
- Added decisionNotificationHandler and addTrackNotificationHandler in Optimizely client 
- Added some unit tests just to verify all conditions of adding DecisionHandler and trackNoitificationHandler
=> Feat: Added notification listener handler functions to support latest changes   

CHANGELOG.md, test-app/src/main/java/com/optimizely/ab/android/test_app/SplashScreenActivity.java
- Prepping for the 3.1.0 release
=> chore: Prepare for 3.1.0 release.

CHANGELOG.md
=> (chore): changelog for release

CHANGELOG.md
- Prepare for release of 3.2.1
=> (chore): update changelog for patch release 3.2.1

.travis.yml, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java, build.gradle, test-app/src/main/java/com/optimizely/ab/android/test_app/MyApplication.java
- We want to take advantage of batch processing by default.  So, by default batch event processor is created.
Manually testing using the test app and my own project.
=> (fix): default to batch event processor

CHANGELOG.md
- update the changelog in preparing for 3.3.0 release
=> (chore):update changelog for release

CHANGELOG.md, proguard-rules.txt
- Customer wants us to keep slf4j.  Seems like a reasonable request.
build minified app
=> fix (proguard): added a progruard keep rule for slf4j

android-sdk/src/androidTest/java/com/optimizely/ab/android/sdk/OptimizelyClientTest.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, build.gradle
Added a getOptimizelyConfig API which returns OptimizelyConfig Object containing experiments and features data.
Added simple Unit Test because main functionality of optimizelyConfigService is getting tested in java sdk. 
Tested with FSC Using Java-sdk branch containing optlimizelyConfigSupport api
NOTE: 
We have to wait for Java sdk PR -348 to get merged or fullstack tests will not get passed
=> feat: getOptimizelyConfig support added

CHANGELOG.md
=> chore: prepare for release 3.4.0

.travis.yml, CHANGELOG.md
Add auto spelling check in travis
=> ci(travis): add mdspell

.gitignore, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java, android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerBuilderTest.java, test-app/src/main/java/com/optimizely/ab/android/test_app/MyApplication.java
- Clarify minimum polling interval as 15 mins
- Fix the sample code accordingly
OASIS-5988
=> chore: clarify min polling interval as 15 mins

test-app/src/main/java/com/optimizely/ab/android/test_app/SamplesForAPI.java
- More sample codes for SDK initialization
=> chore: add more sample codes for SDK initialization with options

CHANGELOG.md, README.md, build.gradle
=> chore: prepare for release 3.5.1

CHANGELOG.md, datafile-handler/src/androidTest/java/com/optimizely/ab/android/datafile_handler/DatafileLoaderTest.java, datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileLoader.java
- Prepare for release.
#334 
#333
=> chore: prepare for release and fix unit tests

.travis.yml, build.gradle
- Update the optimizely/android-sdk.git dependencies to versions without known vulnerabilities.
All FSC and unit Tests must pass
All warnings are cleared: [Travis Source clear link](https://travis-ci.org/github/optimizely/android-sdk/jobs/725914520 )
=> Feat: Updated jackson-databind version to latest which has zero direct vulnerabilities

CHANGELOG.md, README.md, build.gradle
=> chore: release 3.7.0

CHANGELOG.md, README.md, build.gradle, test-app/src/main/java/com/optimizely/ab/android/test_app/MyApplication.kt
=> chore: prepare for 3.8.0 release

CHANGELOG.md, build.gradle
=> chore: prepare for release

CHANGELOG.md, README.md
=> chore: change change log

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java, android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java, shared/src/main/java/com/optimizely/ab/android/shared/DatafileConfig.java, shared/src/main/java/com/optimizely/ab/android/shared/WorkerScheduler.java
- Clean up all javadoc warnings
=> fix: clean up all javadoc warnings

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java
- Removed IsValid condition before creating OptimizelyUserContext
- This is to make sure the behavior is same like java sdk
=> Fix: Removed isValidCondition from CreateUserContext

.travis.yml, CHANGELOG.md, android-sdk/build.gradle, build.gradle, datafile-handler/build.gradle, event-handler/build.gradle, shared/build.gradle, test-app/src/main/java/com/optimizely/ab/android/test_app/SamplesForAPI.java, user-profile/build.gradle
- Upload maven artifacts to maven-central (pom, signing)
- Refer to these guide docs:
- https://central.sonatype.org/pages/ossrh-guide.html
- https://central.sonatype.org/pages/working-with-pgp-signatures.html
- https://docs.gradle.org/current/userguide/publishing_maven.html
- OASIS-7439
=> chore: migrate upload repository to maven-central from jcenter

CHANGELOG.md, README.md
=> chore: prepare for release 3.10.1

README.md
- Update README about MavenCentral
=> chore: update README about MavenCentral

CHANGELOG.md, README.md, build.gradle
=> chore: prepare for release 3.10.2

.travis.yml, build.gradle
- travis support for releasing snapshot version
=> chore: add snapshot publish to travis

.travis.yml, build.gradle
- Refactor travis to fix snapshot upload failure
=> chore: refactor travis to fix snapshot upload failure

CHANGELOG.md, README.md, build.gradle
=> chore: prepare for release 3.11.0

CHANGELOG.md, README.md
=> chore: prepare for release 3.11.1

android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java, android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerIntervalTest.java, build.gradle, datafile-handler/build.gradle, datafile-handler/src/androidTest/java/com/optimizely/ab/android/datafile_handler/DatafileLoaderTest.java, datafile-handler/src/androidTest/java/com/optimizely/ab/android/datafile_handler/DatafileWorkerTest.java, datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileCache.java, datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileLoader.java, datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileWorker.java, datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DefaultDatafileHandler.java, event-handler/build.gradle, event-handler/src/androidTest/java/com/optimizely/ab/android/event_handler/DefaultEventHandlerTest.java, event-handler/src/androidTest/java/com/optimizely/ab/android/event_handler/EventClientTest.java, event-handler/src/androidTest/java/com/optimizely/ab/android/event_handler/EventWorkerTest.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/DefaultEventHandler.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventClient.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventDispatcher.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventRescheduler.java, event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventWorker.java, event-handler/src/test/java/com/optimizely/ab/android/event_handler/EventWorkerUnitTest.java, shared/build.gradle, shared/src/androidTest/java/com/optimizely/ab/android/shared/TestWorker.java, shared/src/androidTest/java/com/optimizely/ab/android/shared/WorkerSchedulerTest.java, shared/src/main/java/com/optimizely/ab/android/shared/WorkerScheduler.java
- Add connection constraints to WorkManager requests for datafile-fetch and event-dispatch
- Fix default event-dispatch retry to disabled (configurable)
- Unit tests for DatafileWorker and EventWorker 
- Manual tests with devices
-  OASIS-8025
=> feature(Reachability): add connection checking for datafile-fetch and event-dispatch

CHANGELOG.md, README.md, build.gradle
=> chore: prepare for release 3.13.0

README.md
Updating documentation URLs in the ReadMe that are old.
We updated the URLs of the developer documentation as part of the consolidation of documentation.
N/A
N/A
=> Updating doc URLs

.github/workflows/android.yml
- Git actions updated to run FSC on git actions.
- Need to change travisci-tools branch from `mnoman/gitActions` to `master`
=> feat: updated for fsc git action

build.gradle
- upgrade compileSdkVersion/targetSdkVersion to 33 (Android 13)
- Pass all existing unit tests with Android 13 simulators (not with github actions which not supporting Android 13)
- Manual test with testa-app with Android 13 simulators
- FSSDK-8526
=> chore: upgrade to Android 13

.gitignore, .idea/copyright/FullStack_Copyright.xml, .idea/copyright/profiles_settings.xml
Add a template for copyright header.
- FSSDK-0000 (N/A)
=> chore: fix copyright template

CHANGELOG.md, README.md
Prepare for release 3.13.3.
- FSSDK-0000 (N/A)
=> chore: prepare for release 3.13.3

CHANGELOG.md, build.gradle
Prepare for release 4.0.0-beta
- [FSSDK-8919](https://jira.sso.episerver.net/browse/FSSDK-8919)
=> [FSSDK-8919] chore: prepare for release 4.0.0-beta

CHANGELOG.md
Prepare for release 4.0.0-beta2
- [FSSDK-8919](https://jira.sso.episerver.net/browse/FSSDK-8919)
=> [FSSDK-8919] chore: prepare for release 4.0.0-beta2

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/ENHANCEMENT.yml, .github/ISSUE_TEMPLATE/FEATURE-REQUEST.md, .github/ISSUE_TEMPLATE/config.yml
- Update github issue templates
- All tests should pass
- FSSDK-9552
=> [FSSDK-9552]: Update Github Issue Templates

CHANGELOG.md, build.gradle
- Release 4.0.0-beta3
- FSSDK-9545
=> [FSSDK-9545] chore: release 4.0.0-beta3

CHANGELOG.md, README.md, build.gradle
prepare for release 4.0.0
- [FSSDK-8585](https://jira.sso.episerver.net/browse/FSSDK-8585)
=> [FSSDK-8585] chore: prepare for release 4.0.0

.github/workflows/android.yml
Reverts optimizely/android-sdk#478
=> Revert "[FSSDK-10230] fix: GitHub slug `head_ref` vulnerability resolved"

.github/workflows/android.yml
- Assigned the value of `github.head_ref` to an intermediate environment variable and employ that variable in the shell script.
- https://securitylab.github.com/research/github-actions-untrusted-input/
- https://codeql.github.com/codeql-query-help/javascript/js-actions-command-injection/
- https://securitylab.github.com/advisories/GHSL-2023-110_Wing_Language/
- N / A
- [FSSDK-10230](https://jira.sso.episerver.net/browse/FSSDK-10230)
=> [FSSDK-10230] fix: GitHub slug `head_ref` vulnerability resolved

.github/workflows/android.yml
Instead of directly using variables that can contain user input, new intermediate variables were introduced so that script injection attacks could be mitigated. Also removed unnecessary use of ${{ }} as using it makes the file vulnerable.
- [FSSDK-10665](https://jira.sso.episerver.net/browse/FSSDK-10665)
=> [FSSDK-10665] fix: Github Actions YAML files vulnerable to script injection

CHANGELOG.md, README.md
- Prepare for release 5.0.0
- All tests should be passed
- [FSSDK-10841](https://jira.sso.episerver.net/browse/FSSDK-10841)
=> [FSSDK-10841] chore: release 5.0.0

.github/workflows/android.yml
Updating workflow versions
- https://jira.sso.episerver.net/browse/EC3-1687
=> EC3-1687 updating workflows

CHANGELOG.md, README.md
-Prepare for release 5.0.1
- FSSDK-11464
=> [FSSDK-11464] chore: release 5.0.1
